language: python

dist: jammy

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
install:
  pip install -r requirements.txt;
script:
  - nosetests -vv
  - script/hash.sh
  - python -m hashit -bf test/support/example.bin --hash-type CRC16 --verify BD68
notifications:
  email:
    - depostorivo@gmail.com
